# Generated by Django 6.0.6 on 2026-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemsettings_user_device_info_user_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_data',
            field=models.TextField(blank=True),
        ),
    ]
