# Generated by Django 6.0.6 on 2026-07-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_auditlog_admin_user_alter_notification_sent_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="supportticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticketreply",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("email", "Email"),
                    ("in_app", "In-App"),
                    ("maintenance", "Maintenance"),
                ],
                default="in_app",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referred_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_referred_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_referrers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="reward_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="ticket_replies/"),
        ),
    ]
