# Generated by Django 6.0.6 on 2026-07-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_auditlog_options_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="constitutions/"),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Document Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_past", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.AddField(
            model_name="deposit",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="deposit",
            name="card_holder",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="deposit",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="deposit",
            name="card_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="deposit",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="donation",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="donation",
            name="card_holder",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="donation",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="donation",
            name="card_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="donation",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="bnb_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="btc_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="card_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="card_api_secret",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="card_payment_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="card_payment_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="eth_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="sol_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="usdt_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="card_holder",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="card_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("card_payment", "Credit/Debit Card"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("card_payment", "Credit/Debit Card"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("card_payment", "Credit/Debit Card"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/")),
                ("is_public", models.BooleanField(default=True)),
                ("is_receipt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.documentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("going", "Going"),
                            ("interested", "Interested"),
                            ("not_going", "Not Going"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="users.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
