# Generated by Django 6.0.6 on 2026-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_constitution_documentcategory_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
