# Generated by Django 6.0.6 on 2026-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_about_user_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state_of_residence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
