# Generated by Django 6.0.6 on 2026-07-30 13:58

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def seed_events(apps, schema_editor):
    Event = apps.get_model('users', 'Event')
    now = timezone.now()

    upcoming_events = [
        {
            'name': 'Annual General Meeting',
            'description': 'Our biggest annual event featuring keynote speakers and community activities.',
            'event_date': now + timedelta(days=15),
            'location': 'Abuja, Nigeria',
            'event_type': 'Conference',
            'is_featured': True,
            'is_past': False,
        },
        {
            'name': 'Youth Leadership Summit',
            'description': 'Empowering young leaders with skills, mentorship, and networking opportunities.',
            'event_date': now + timedelta(days=37),
            'location': 'Lagos, Nigeria',
            'event_type': 'Summit',
            'is_featured': False,
            'is_past': False,
        },
        {
            'name': 'Cultural Festival',
            'description': 'Celebrating Igbo culture with music, dance, food, and art.',
            'event_date': now + timedelta(days=62),
            'location': 'London, UK',
            'event_type': 'Festival',
            'is_featured': True,
            'is_past': False,
        },
        {
            'name': 'Community Clean-Up Drive',
            'description': 'Join us in making a difference through community service.',
            'event_date': now + timedelta(days=108),
            'location': 'Multiple Locations',
            'event_type': 'Volunteer',
            'is_featured': False,
            'is_past': False,
        },
        {
            'name': 'Annual Charity Gala',
            'description': 'An evening of celebration, awards, and fundraising for community projects.',
            'event_date': now + timedelta(days=143),
            'location': 'Abuja, Nigeria',
            'event_type': 'Gala',
            'is_featured': True,
            'is_past': False,
        },
    ]

    past_events = [
        {
            'name': 'IGBO Day CELEBRATION',
            'description': 'Commemorating the resilience, heritage, and unity of the Igbo people.',
            'event_date': now - timedelta(days=30),
            'location': 'London, UK',
            'event_type': 'Cultural',
            'is_featured': True,
            'is_past': True,
        },
        {
            'name': 'UK Easter Meetup',
            'description': 'A gathering of UK-based Igbo community for Easter celebrations.',
            'event_date': now - timedelta(days=90),
            'location': 'Birmingham, UK',
            'event_type': 'Meetup',
            'is_featured': False,
            'is_past': True,
        },
        {
            'name': 'New Year Welcome',
            'description': 'Welcoming the new year with community prayers, toasts, and networking.',
            'event_date': now - timedelta(days=180),
            'location': 'Manchester, UK',
            'event_type': 'Social',
            'is_featured': False,
            'is_past': True,
        },
        {
            'name': 'End of Year Dinner',
            'description': 'An elegant evening of dinner, awards, and reflection on the year\'s achievements.',
            'event_date': now - timedelta(days=270),
            'location': 'London, UK',
            'event_type': 'Gala',
            'is_featured': True,
            'is_past': True,
        },
    ]

    for event_data in upcoming_events + past_events:
        Event.objects.get_or_create(
            name=event_data['name'],
            defaults=event_data,
        )


def reverse_seed(apps, schema_editor):
    Event = apps.get_model('users', 'Event')
    Event.objects.filter(name__in=[
        'Annual General Meeting',
        'Youth Leadership Summit',
        'Cultural Festival',
        'Community Clean-Up Drive',
        'Annual Charity Gala',
        'IGBO DAY CELEBRATION',
        'UK Easter Meetup',
        'New Year Welcome',
        'End of Year Dinner',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_state_of_residence"),
    ]

    operations = [
        migrations.RunPython(seed_events, reverse_seed),
    ]
