# Generated by Django 6.0.7 on 2026-08-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_seed_events"),
    ]

    operations = []
