# Generated by Django 6.0.6 on 2026-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="gallery_media/"),
        ),
    ]
