# Generated by Django 6.0.6 on 2026-08-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_statechapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="users.announcement",
            ),
        ),
    ]
