# Generated by Django 6.0.6 on 2026-08-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_user_to_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="card_expiry",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="card_holder",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="card_last_four",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="transaction_reference",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="card_expiry",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="card_holder",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="card_last_four",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="transaction_reference",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="card_expiry",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="card_holder",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="card_last_four",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="transaction_reference",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
