# Generated by Django 6.0.6 on 2026-08-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_partner_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="page_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("about", "About Us"),
                    ("organizational_structure", "Organizational Structure"),
                    ("state_chapters", "State Chapters"),
                    ("achievements", "Achievements"),
                    ("executive_leadership", "Executive Leadership"),
                    ("constitution", "Constitution"),
                    ("refund_policy", "Refund Policy"),
                    ("privacy_policy", "Privacy Policy"),
                    ("terms_conditions", "Terms & Conditions"),
                    ("cookie_policy", "Cookie Policy"),
                    ("mission_vision", "Mission & Vision"),
                ],
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
