# Generated by Django 6.0.6 on 2026-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_galleryimage_media_type_alter_pagecontent_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
