# Generated by Django 6.0.6 on 2026-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="meta_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="meta_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
