# Generated by Django 6.0.6 on 2026-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_pagecontent_meta_description_pagecontent_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL for video gallery items.",
                max_length=300,
                null=True,
            ),
        ),
    ]
