# Generated by Django 6.0.6 on 2026-09-28 11:25

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_add_galleryimage_youtube_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("data", models.BinaryField()),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=150
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Document blobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="constitution",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=users.storage.DatabaseFileStorage(base_url=None, location=""),
                upload_to="constitutions/",
            ),
        ),
    ]
